### ISSUE TITLE
supplementary materials not found~

### ISSUE THREAD

**Issue by tryhere** [aim-uofa/DyCo3D#1]
Thank you for your outstanding work! 
Where can I find your supplementary materials? I want to learn about the difference between your clustering algorithm and pointgroup~

**Comment by tonghe90** [comment]
Thanks for your interest. We will release the supplementary materials recently or you can leave the email address, I will let you know when I publish it.

**Comment by tpzou** [comment]
So is this paper submited for CVPR 2021, and when the code will be released?  I also want to ask how to calculate the AP as there is no score. Is that use classification and the mask quality as SOLOv2? (I haven't read the code of CondIns)

**Comment by Wei-i** [comment]
Hi, thanks for your great work. 
I have read CondInst but I am not familiar with instance segmentation  on  `point cloud`. 
I also want to know how I can find your supplementary materials.
I would be grateful if you could reply for me~

**Comment by tonghe90** [comment]
@Wei-i We will release an extended version recently. You can also leave your email, I can send it to you.

**Comment by Wei-i** [comment]
Thanks for your quick relpy.
My email is chenwei1997@stu.xmu.edu.cn.

It may help me to understand some import details of DyCo3D implementation.
BTW, I am confused about some sentences below in this paper.
(1) During training, the ground truth for $C^z$ if it has the largest number of points in $C^z$.  
What is the meaning of `largets number of points`? For a predicted mask, doesn’t it only contain one specific category of mask? 

(2) $\mathcal 1$ is an indicator function, showing the loss is only computed on the points that have `identical semantic labels` with group $C^z$

From the paper, I think a cluster belongs to semantic prediction from `Seg Head` and contains the points which belong to same semantic label. But it seems I misunderstood.

**Comment by qiruiw** [comment]
@tonghe90 Do you release the extended version or supplementary materials? Or can you send it to my email? bitwqr@gmail.com

**Comment by tonghe90** [comment]
@qiruiw The extended version of Dyco3D can be found here: https://arxiv.org/abs/2107.08392, which includes the supplementary materials of Dyco3d
