### ISSUE TITLE
How to calculate the single AP 

### ISSUE THREAD

**Issue by tpzou** [aim-uofa/DyCo3D#3]
I want to ask how to calculate the single AP as there is no dirct score. Is that use classification and the mask quality as SOLOv2? (I haven't read the code of CondIns)

**Comment by tonghe90** [comment]
For ScanNetV2, we follow the metric computation as in PointGroup. Please check the code for details. For S3DIS, we report the metric from ASIS.

**Comment by tpzou** [comment]
> For ScanNetV2, we follow the metric computation as in PointGroup. Please check the code for details. For S3DIS, we report the metric from ASIS.

@tonghe90 , thanks for your reply. I mean, as best as I know, scores are necessary for computing the AP. As there is no explicit **Score Calculation**, how to compute the Ap?

**Comment by tonghe90** [comment]
@tpzou as described in the paper, we use the mean value of the semantic scores among the foreground points. Also, you can introduce an extra score net (the same as PointGroup), to estimate the quality of the proposal.
