### ISSUE TITLE
Prepare the ScanNet dataset 

### ISSUE THREAD

**Issue by KangchengLiu** [aim-uofa/DyCo3D#6]
Code to prepare the ScanNet dataset can not be found. Any code to prepare the train/val/test set?

**Comment by tonghe90** [comment]
@KangchengLiu We follow the pipeline from PointGroup: https://github.com/dvlab-research/PointGroup/tree/master/dataset/scannetv2.

**Comment by KangchengLiu** [comment]
Thanks! Any code to split the train/val/test set from the raw downloaded Scannet v2 dataset?

**Comment by tonghe90** [comment]
https://github.com/ScanNet/ScanNet/tree/master/Tasks/Benchmark
