### ISSUE TITLE
How to test on my own point cloud data using DyCo3D?

### ISSUE THREAD

**Issue by Yellowshuohahaha** [aim-uofa/DyCo3D#7]
My point cloud data is in pcd format, which contains many workpiece. Can I use DyCo3D to segment each workpiece with pretrained model and how to do that? I‘m a new guy in this field and looking forward to your reply.

**Comment by tonghe90** [comment]
@Yellowshuohahaha What do you mean by workpiece? Are that separated blocks?

**Comment by Yellowshuohahaha** [comment]
![image](https://user-images.githubusercontent.com/48409315/126958769-482bf393-4fa2-42f3-8541-d0e101574ca8.png)
Just like this.

**Comment by tonghe90** [comment]
I am not sure. But from the data you provide, I think it may not work by directly using the model we provide, as it is trained for indoor scenes and is quite different from this.

**Comment by Yellowshuohahaha** [comment]
Thanks a lot！ But I would like to ask if you provide a api for inference and I want to test on it.

**Comment by tonghe90** [comment]
You can check this function: https://github.com/aim-uofa/DyCo3D/blob/main/model/pointgroup/pointgroup.py#L577
