### ISSUE TITLE
proposal_idx empty in validation

### ISSUE THREAD

**Issue by FeiYuejiao** [aim-uofa/DyCo3D#8]
When I was validating on ScanNetv2, I encounterd the problem in the function generate_proposal(). 
```
[2021-07-27 11:48:44,183  INFO  test.py  line 44  41515]  >>>>>>>>>>>>>>>> Start Evaluation >>>>>>>>>>>>>>>>                                                                                                                [585/15021]
[2021-07-27 11:48:53,470  INFO  scannetv2_inst.py  line 108  41515]  Testing samples (val): 312
/home/sysadmin/.fei/DyCo3D/model/pointgroup/pointgroup.py:432: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729047590/work/torch/csrc/utils/python_arg_parser.cpp:882.)
  proposal_id_n = ((mask_logits[n] > threshold) + (seg_pred == inst_pred_seg_label[n].item()) > 1).nonzero().squeeze(dim=1)
Traceback (most recent call last):
  File "test.py", line 265, in <module>
    test(model, model_fn, data_name, cfg.test_epoch)
  File "test.py", line 64, in test
    preds = model_fn(batch, model, epoch)
  File "/home/sysadmin/.fei/DyCo3D/model/pointgroup/pointgroup.py", line 605, in test_model_fn
    ret = model(input_, p2v_map, coords_float, coords[:, 0].int(), batch_offsets, epoch, ins_sample_num=-1, training=False)
  File "/home/sysadmin/.conda/envs/mm3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/sysadmin/.fei/DyCo3D/model/pointgroup/pointgroup.py", line 568, in forward
    min_pts_num=50)
  File "/home/sysadmin/.fei/DyCo3D/model/pointgroup/pointgroup.py", line 445, in generate_proposal
    proposal_idx = torch.cat(proposal_idx, dim=0)
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty li
st of Tensors.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched
, VmapMode].
```

The problem is in the for loop that all proposal_id_n is a tensor of zero. However I think my dataset is well processed. 
```
        for n in range(n_inst):
            proposal_id_n = ((mask_logits[n] > threshold) + (seg_pred == inst_pred_seg_label[n].item()) > 1).nonzero().squeeze(dim=1)
            score = mask_logits[n][proposal_id_n].mean()
            seg_label = inst_pred_seg_label[n]
            if proposal_id_n.size(0) < min_pts_num:
                continue
            proposal_id_n = batch_id[proposal_id_n.long()].unsqueeze(dim=1)
            id_proposal_id_n = torch.cat([torch.ones_like(proposal_id_n)*num, proposal_id_n], dim=1)
            num += 1
            tmp = proposal_len[-1]
            proposal_len.append(proposal_id_n.size(0)+tmp)
            proposal_idx.append(id_proposal_id_n)
            scores.append(score)
```
Could you give me some advice？ Thanks.

**Comment by tonghe90** [comment]
Hi is this error exists for every scan or just some particular scan in the for loop?

**Comment by FeiYuejiao** [comment]
Hi, for every scan and every instance in the for loop, `proposal_id_n = ((mask_logits[n] > threshold) + (seg_pred == inst_pred_seg_label[n].item()) > 1).nonzero().squeeze(dim=1)` returns zero.

**Comment by tonghe90** [comment]
@FeiYuejiao Sorry, I can't repeat your error. I will upload the processed data tomorrow. I would suggest you check which part leads to proposal_id_n being zero, the logits, or the seg_pred.

**Comment by lzhangbj** [comment]
Here is the problem
https://github.com/aim-uofa/DyCo3D/blob/f93b31add32777834999948721562ee3ee8920b6/model/pointgroup/pointgroup.py#L432

change this line to 
`proposal_id_n = ((mask_logits[n] > threshold) & (seg_pred == inst_pred_seg_label[n].item())).nonzero().squeeze(dim=1)`

sum of two boolean tensors will never be larger than 1 (True), which makes the number of proposals become zero. Maybe it is the version of Pytorch that leads to this error, as the code is built upon the outdated pytorch 1.1.

**Comment by lzhangbj** [comment]
Here is the problem
https://github.com/aim-uofa/DyCo3D/blob/f93b31add32777834999948721562ee3ee8920b6/model/pointgroup/pointgroup.py#L432

change this line to 
`proposal_id_n = ((mask_logits[n] > threshold) & (seg_pred == inst_pred_seg_label[n].item())).nonzero().squeeze(dim=1)`

sum of two boolean tensors will never be larger than 1 (True), which makes the number of proposals become zero. Maybe it is the version of Pytorch that leads to this error, as the code is built upon the outdated pytorch 1.1.

**Comment by tonghe90** [comment]
https://cloudstor.aarnet.edu.au/plus/s/OduLRCyKpDoL3pX
